Sources: 

1. https://medium.com/biaslyai/learn-pytorch-basics-6d433f186b7a#annotations:RuQUgvymEemFu8tmdAybiw
2. https://johnwlambert.github.io/pytorch-tutorial/#annotations:h5Vj4vylEemviMtX6J8WuQ
3. https://jhui.github.io/2018/02/09/PyTorch-Basic-operations/#annotations:4-d5lvylEemWP6uACcixlg

In [1]:
import torch 

In [2]:
# Create a tensor
torch.Tensor([[1,2], [3,4]])

tensor([[1., 2.],
        [3., 4.]])

In [3]:
# create 2 x 3 tensor with zero values
torch.Tensor(2,3)

tensor([[-0.0000,  0.0000, -0.0000],
        [ 0.0000,  0.0000,  0.0000]])

In [4]:
# create 2x3 tensor with random uniform values between -1, 1
torch.Tensor(2, 3).uniform_(-1,1)

tensor([[ 0.3845,  0.1931, -0.7631],
        [ 0.4475, -0.8197,  0.1667]])

In [5]:
torch.empty(1,3)

tensor([[-6.5972e-38,  4.5619e-41, -9.4068e-36]])

Tensor Accessing Examples

In [7]:
tensor = torch.Tensor([[1,2], [3,4]])
tensor

tensor([[1., 2.],
        [3., 4.]])

In [9]:
# Replacing an element at 0,1
tensor[0][1] = 433
tensor

tensor([[  1., 433.],
        [  3.,   4.]])

In [12]:
# Get an elemen at position 1, 0
print(tensor[1][0])
print(tensor[1][0].item())

tensor(3.)
3.0


In [72]:
# Indexing examples
x = torch.arange(4*3)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [73]:
x = x.reshape(3,2,2)
x

tensor([[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]],

        [[ 8,  9],
         [10, 11]]])

In [74]:
x[0, :, :] # prints 0th channel image

tensor([[0, 1],
        [2, 3]])

In [75]:
x[1, :, :] # prints 1st channel image

tensor([[4, 5],
        [6, 7]])

In [76]:
x[2, :, :] # prints 2nd channel image

tensor([[ 8,  9],
        [10, 11]])

In [77]:
# index to get all channels for 0th row, 0th col
x[:, 0, 0]

tensor([0, 4, 8])

In [92]:
x

tensor([[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]],

        [[ 8,  9],
         [10, 11]]])

In [93]:
# Adding a batch dimension 
print(x.unsqueeze(0).shape)
print(x.view(6, 2))

torch.Size([1, 3, 2, 2])
tensor([[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9],
        [10, 11]])


Reshaping tensors

In [80]:
x

tensor([[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]],

        [[ 8,  9],
         [10, 11]]])

In [78]:
# squeeze returns tensor with all dimensions of input of
# size 1 removed
x.squeeze().shape 

torch.Size([3, 2, 2])

In [83]:
# unsqueeze(i) returns new tensor with dimension of size one
# inserted at position (i)
print(x.unsqueeze(0).size())
print(x.unsqueeze(0).dim())
print(x.unsqueeze(0))

torch.Size([1, 3, 2, 2])
4
tensor([[[[ 0,  1],
          [ 2,  3]],

         [[ 4,  5],
          [ 6,  7]],

         [[ 8,  9],
          [10, 11]]]])


In [82]:
# unsqueeze(i) returns new tensor with dimension of size one
# inserted at position (i)
print(x.unsqueeze(1).size())
print(x.unsqueeze(1).dim())
print(x.unsqueeze(1))

tensor([[[[ 0,  1],
          [ 2,  3]]],


        [[[ 4,  5],
          [ 6,  7]]],


        [[[ 8,  9],
          [10, 11]]]])
torch.Size([3, 1, 2, 2])
4


In [84]:
# unsqueeze(i) returns new tensor with dimension of size one
# inserted at position (i)
print(x.unsqueeze(2).size())
print(x.unsqueeze(2).dim())
print(x.unsqueeze(2))

torch.Size([3, 2, 1, 2])
4
tensor([[[[ 0,  1]],

         [[ 2,  3]]],


        [[[ 4,  5]],

         [[ 6,  7]]],


        [[[ 8,  9]],

         [[10, 11]]]])


In [85]:
# unsqueeze(i) returns new tensor with dimension of size one
# inserted at position (i)
print(x.unsqueeze(3).size())
print(x.unsqueeze(3).dim())
print(x.unsqueeze(3))

torch.Size([3, 2, 2, 1])
4
tensor([[[[ 0],
          [ 1]],

         [[ 2],
          [ 3]]],


        [[[ 4],
          [ 5]],

         [[ 6],
          [ 7]]],


        [[[ 8],
          [ 9]],

         [[10],
          [11]]]])


In [87]:
# unsqueeze(i) returns new tensor with dimension of size one
# inserted at position (i)
print(x.unsqueeze(-1).size())
print(x.unsqueeze(-1).dim())
print(x.unsqueeze(-1))

torch.Size([3, 2, 2, 1])
4
tensor([[[[ 0],
          [ 1]],

         [[ 2],
          [ 3]]],


        [[[ 4],
          [ 5]],

         [[ 6],
          [ 7]]],


        [[[ 8],
          [ 9]],

         [[10],
          [11]]]])


In [89]:
# unsqueeze(i) returns new tensor with dimension of size one
# inserted at position (i)
print(x.unsqueeze(-2).size())
print(x.unsqueeze(-2).dim())
print(x.unsqueeze(-2))

torch.Size([3, 2, 1, 2])
4
tensor([[[[ 0,  1]],

         [[ 2,  3]]],


        [[[ 4,  5]],

         [[ 6,  7]]],


        [[[ 8,  9]],

         [[10, 11]]]])


In [90]:
# unsqueeze(i) returns new tensor with dimension of size one
# inserted at position (i)
print(x.unsqueeze(-3).size())
print(x.unsqueeze(-3).dim())
print(x.unsqueeze(-3))

torch.Size([3, 1, 2, 2])
4
tensor([[[[ 0,  1],
          [ 2,  3]]],


        [[[ 4,  5],
          [ 6,  7]]],


        [[[ 8,  9],
          [10, 11]]]])


In [91]:
# unsqueeze(i) returns new tensor with dimension of size one
# inserted at position (i)
print(x.unsqueeze(-4).size())
print(x.unsqueeze(-4).dim())
print(x.unsqueeze(-4))

torch.Size([1, 3, 2, 2])
4
tensor([[[[ 0,  1],
          [ 2,  3]],

         [[ 4,  5],
          [ 6,  7]],

         [[ 8,  9],
          [10, 11]]]])


Tensor Slicing Examples

In [17]:
sliceTensor = torch.Tensor([[1,2,3], [4,5,6], [7,8,9]])
sliceTensor

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [18]:
# elements from every row, first column
sliceTensor[:, 0]

tensor([1., 4., 7.])

In [19]:
# elements from every row, last column
sliceTensor[:, -1]

tensor([3., 6., 9.])

In [21]:
# all elements on the second row
sliceTensor[1, :]

tensor([4., 5., 6.])

In [22]:
# all elements from the first two rows
sliceTensor[0:2, :]

tensor([[1., 2., 3.],
        [4., 5., 6.]])

Get Tensor Information

In [25]:
tensor = torch.Tensor([[1,2], [3,4]])
tensor

tensor([[1., 2.],
        [3., 4.]])

In [29]:
print(tensor.type())
print(tensor.shape)
print(tensor.size())
print(tensor.dim())

torch.FloatTensor
torch.Size([2, 2])
torch.Size([2, 2])
2


In [31]:
# reshape tensor in n x m tensor
reshaped1 = tensor.view(1, 4)
print(reshaped1)
print(reshaped1.size())
print(reshaped1.dim())

tensor([[1., 2., 3., 4.]])
torch.Size([1, 4])
2


In [33]:
reshaped2 = tensor.view(4, 1)
print(reshaped2)
print(reshaped2.size())
print(reshaped2.dim())

tensor([[1.],
        [2.],
        [3.],
        [4.]])
torch.Size([4, 1])
2


# Conversion between numpy ndarray to pytorch tensor


In [34]:
import numpy as np

In [36]:
npArray = np.random.randn(2,2)

# From ndarray to tensor
toTensor = torch.from_numpy(npArray)
print(toTensor)


tensor([[-0.6859,  0.7078],
        [-0.2202, -0.6382]], dtype=torch.float64)


In [37]:
# From tensor to numpy ndarrray
toArray = toTensor.numpy()
print(toArray)

[[-0.68589138  0.70778997]
 [-0.22016197 -0.6382417 ]]


In [64]:
a = torch.Tensor([[1,1,4,5], [6,7,3,2], [5,5,5,2]])
b = torch.Tensor([[0,4,2,2], [1,1,3,1], [1,9,7,8]])
c = torch.Tensor([[1,1], [2,2], [0,5]])
print(a)
print(b)
print(c)

tensor([[1., 1., 4., 5.],
        [6., 7., 3., 2.],
        [5., 5., 5., 2.]])
tensor([[0., 4., 2., 2.],
        [1., 1., 3., 1.],
        [1., 9., 7., 8.]])
tensor([[1., 1.],
        [2., 2.],
        [0., 5.]])


In [66]:
# transpose
a.t()

tensor([[1., 6., 5.],
        [1., 7., 5.],
        [4., 3., 5.],
        [5., 2., 2.]])

In [57]:
# cross product
a.cross(b)

tensor([[  1.,  58.,   6.,  14.],
        [ -1.,  11., -18., -36.],
        [  1., -27.,   6.,   1.]])

In [69]:
# matrix product
a.t().mm(c)

tensor([[13., 38.],
        [15., 40.],
        [10., 35.],
        [ 9., 19.]])