Sources: 

1. https://medium.com/biaslyai/learn-pytorch-basics-6d433f186b7a#annotations:RuQUgvymEemFu8tmdAybiw
2. https://johnwlambert.github.io/pytorch-tutorial/#annotations:h5Vj4vylEemviMtX6J8WuQ
3. https://jhui.github.io/2018/02/09/PyTorch-Basic-operations/#annotations:4-d5lvylEemWP6uACcixlg

In [1]:
import torch 

In [2]:
# Create a tensor
torch.Tensor([[1,2], [3,4]])

tensor([[1., 2.],
        [3., 4.]])

In [3]:
# create 2 x 3 tensor with zero values
torch.Tensor(2,3)

tensor([[-0.0000,  0.0000, -0.0000],
        [ 0.0000,  0.0000,  0.0000]])

In [4]:
# create 2x3 tensor with random uniform values between -1, 1
torch.Tensor(2, 3).uniform_(-1,1)

tensor([[ 0.3845,  0.1931, -0.7631],
        [ 0.4475, -0.8197,  0.1667]])

In [5]:
torch.empty(1,3)

tensor([[-6.5972e-38,  4.5619e-41, -9.4068e-36]])

Tensor Slicing Examples

In [7]:
tensor = torch.Tensor([[1,2], [3,4]])
tensor

tensor([[1., 2.],
        [3., 4.]])

In [9]:
# Replacing an element at 0,1
tensor[0][1] = 433
tensor

tensor([[  1., 433.],
        [  3.,   4.]])

In [12]:
# Get an elemen at position 1, 0
print(tensor[1][0])
print(tensor[1][0].item())

tensor(3.)
3.0


Tensor Slicing Examples

In [17]:
sliceTensor = torch.Tensor([[1,2,3], [4,5,6], [7,8,9]])
sliceTensor

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [18]:
# elements from every row, first column
sliceTensor[:, 0]

tensor([1., 4., 7.])

In [19]:
# elements from every row, last column
sliceTensor[:, -1]

tensor([3., 6., 9.])

In [21]:
# all elements on the second row
sliceTensor[1, :]

tensor([4., 5., 6.])

In [22]:
# all elements from the first two rows
sliceTensor[0:2, :]

tensor([[1., 2., 3.],
        [4., 5., 6.]])

Get Tensor Information

In [25]:
tensor = torch.Tensor([[1,2], [3,4]])
tensor

tensor([[1., 2.],
        [3., 4.]])

In [29]:
print(tensor.type())
print(tensor.shape)
print(tensor.size())
print(tensor.dim())

torch.FloatTensor
torch.Size([2, 2])
torch.Size([2, 2])
2


In [31]:
# reshape tensor in n x m tensor
reshaped1 = tensor.view(1, 4)
print(reshaped1)
print(reshaped1.size())
print(reshaped1.dim())

tensor([[1., 2., 3., 4.]])
torch.Size([1, 4])
2


In [ ]:
reshaped2 = tensor.view(4, 1)
print(reshaped2)
print(reshaped2.size())
print(reshaped2.dim())